const USERS=[
{u:'org1',p:'1234',r:'organizador'},{u:'org2',p:'1234',r:'organizador'},
{u:'viajero1',p:'1234',r:'viajero'},{u:'viajero2',p:'1234',r:'viajero'},
{u:'taxi1',p:'1234',r:'taxista'},{u:'taxi2',p:'1234',r:'taxista'}];
const K={trips:'trips_v5',notifs:'notifs_v5',session:'session_v2'};
const $=id=>document.getElementById(id);const read=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const trips=()=>read(K.trips,[]), setTrips=v=>write(K.trips,v), notifs=()=>read(K.notifs,[]), setNotifs=v=>write(K.notifs,v);
const session=()=>JSON.parse(localStorage.getItem(K.session)||'null');
function push(role,user,text,id){const n=notifs();n.unshift({role,user,text,id,at:new Date().toISOString()});setNotifs(n);}const estado=v=>`V:${v.cv?'✅':'⏳'} T:${v.ct?'✅':'⏳'}`;

function setView(role){['organizador','viajero','taxista'].forEach(r=>$('view-'+r).classList.add('hidden'));$('view-'+role).classList.remove('hidden');$('panel-title').textContent=`${role} · ${session().u}`;}

function renderOrg(){const body=$('tabla');const data=trips();body.innerHTML=data.length?'':'<tr><td colspan="7">Sin viajes</td></tr>';data.forEach(v=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${v.empresa}</td><td>${v.viajero}</td><td>${v.domicilio} → ${v.aeropuerto}</td><td>${v.fecha} ${v.hora}</td><td>${v.taxista}</td><td>${estado(v)}</td><td><button data-id="${v.id}" class="edit-org">Editar</button></td>`;body.appendChild(tr);});document.querySelectorAll('.edit-org').forEach(b=>b.onclick=()=>{const t=trips().find(x=>x.id===b.dataset.id);if(!t)return;['trip-id','empresa','viajero','domicilio','aeropuerto','fecha','hora','taxista'].forEach(k=>$(k).value=t[k]||'');});}
function card(v,role){const f=role==='viajero'?'cv':'ct';return `<article class='trip'><p><b>${v.domicilio}</b> → ${v.aeropuerto}</p><p>${v.fecha} ${v.hora} · ${estado(v)}</p><button class='confirm' data-id='${v.id}' data-f='${f}'>Confirmar</button><button class='edit-mobile' data-id='${v.id}' data-role='${role}'>Modificar domicilio/hora</button></article>`;}
function renderMobile(role){const me=session().u;const mine=trips().filter(t=>t[role]===me);const l=role==='viajero'?'lista-v':'lista-t';const nl=role==='viajero'?'notif-v':'notif-t';$(l).innerHTML=mine.map(v=>card(v,role)).join('')||'<p>Sin viajes</p>';$(nl).innerHTML=notifs().filter(n=>n.role===role&&n.user===me).map(n=>`<li>${n.text}</li>`).join('')||'<li>Sin notificaciones</li>';
 document.querySelectorAll('.confirm').forEach(b=>b.onclick=()=>{const all=trips();const t=all.find(x=>x.id===b.dataset.id);if(!t)return;t[b.dataset.f]=true;setTrips(all);push('viajero',t.viajero,`Estado actualizado ${estado(t)}`,t.id);push('taxista',t.taxista,`Estado actualizado ${estado(t)}`,t.id);render();});
 document.querySelectorAll('.edit-mobile').forEach(b=>b.onclick=()=>{const all=trips();const t=all.find(x=>x.id===b.dataset.id);if(!t)return;const d=prompt('Nuevo domicilio',t.domicilio);if(d===null)return;const h=prompt('Nueva hora (HH:MM)',t.hora);if(h===null)return;t.domicilio=d||t.domicilio;t.hora=h||t.hora;t.cv=false;t.ct=false;setTrips(all);push('viajero',t.viajero,`Reserva modificada por ${b.dataset.role}. Reconfirmar.`,t.id);push('taxista',t.taxista,`Reserva modificada por ${b.dataset.role}. Reconfirmar.`,t.id);render();});}

function render(){const s=session();if(!s)return;setView(s.r);if(s.r==='organizador')renderOrg();if(s.r==='viajero')renderMobile('viajero');if(s.r==='taxista')renderMobile('taxista');}
$('login-form').onsubmit=e=>{e.preventDefault();const u=$('user').value.trim(),p=$('pass').value;const f=USERS.find(x=>x.u===u&&x.p===p);if(!f){$('auth-msg').textContent='Credenciales inválidas';return;}localStorage.setItem(K.session,JSON.stringify(f));$('auth').classList.add('hidden');$('app').classList.remove('hidden');render();};
$('logout').onclick=()=>{localStorage.removeItem(K.session);location.reload();};
$('trip-form').onsubmit=e=>{e.preventDefault();const id=$('trip-id').value;const p={empresa:$('empresa').value.trim(),viajero:$('viajero').value.trim(),domicilio:$('domicilio').value.trim(),aeropuerto:$('aeropuerto').value.trim(),fecha:$('fecha').value,hora:$('hora').value,taxista:$('taxista').value.trim()};const all=trips();if(id){const i=all.findIndex(x=>x.id===id);all[i]={...all[i],...p,cv:false,ct:false};push('viajero',p.viajero,'Reserva modificada por organizador. Reconfirmar.',id);push('taxista',p.taxista,'Reserva modificada por organizador. Reconfirmar.',id);}else{const n={id:crypto.randomUUID(),...p,cv:false,ct:false};all.push(n);push('viajero',p.viajero,'Nuevo viaje asignado.',n.id);push('taxista',p.taxista,'Nuevo viaje asignado.',n.id);}setTrips(all);$('trip-form').reset();$('trip-id').value='';$('mensaje').textContent='Guardado.';render();};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
if(session()){$('auth').classList.add('hidden');$('app').classList.remove('hidden');render();}
